name: number_inc_dec
description: A flutter widget which accepts numeric values with buttons to increment and decrement.
version: 0.8.0
homepage: https://github.com/Abhilash-Chandran/number_inc_dec

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter  
  path: ^1.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:    
  uses-material-design: true