name: Update version wiki

on:
  workflow_dispatch:

jobs:
  update-version-wiki:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          path: maaster
      - name: Checkout the wiki repo
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: check wiki repo content
        run: |
          cd wiki && ls -al
